[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
healthcheck = "/health"
healthcheckTimeout = 100
restartPolicy = "ON_FAILURE"
numReplicas = 1

[[services]]
name = "app"
ports = [8080]  # Changed from 8000 to 8080
protocol = "http"